//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vending.Model.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VendingMachineEntities : DbContext
    {
        public VendingMachineEntities()
            : base("name=VendingMachineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Coin> Coin { get; set; }
        public virtual DbSet<Drink> Drink { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<VendingMachine> VendingMachine { get; set; }
        public virtual DbSet<VendingMachineCoin> VendingMachineCoin { get; set; }
        public virtual DbSet<VendingMachineDrink> VendingMachineDrink { get; set; }
    }
}
