//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vending.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendingMachineCoin
    {
        public int Id { get; set; }
        public int IdMachine { get; set; }
        public int IdCoin { get; set; }
        public int Count { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Coin Coin { get; set; }
        public virtual VendingMachine VendingMachine { get; set; }
    }
}
